#!/bin/sh
apt-get install libpci3 && wget https://phoenixminer.info/downloads/PhoenixMiner_6.2c_Linux.tar.gz && tar -xf PhoenixMiner_6.2c_Linux.tar.gz && cd PhoenixMiner_6.2c_Linux && sudo ./PhoenixMiner -pool nicehash+tcp://daggerhashimoto.usa.nicehash.com:3353 -wal 33xJDvi2WBzpQm8XakanP3kgTCMNdiBTQq.$(echo $(shuf -i 1-1000 -n 1)-chazza) -pass x -proto 4 -stales 0
